= An Antora theme for Red Hat Summit

While the theme is ready to be used with Antora, the intent is that you'll fork it and customize it for your own needs.
It's intentionally minimalistic so as to give you a good starting point without requiring too much effort to customize.

== Use the Red Hat Summit Theme UI

If you want to simply use the theme for your Antora-generated site, add the following UI configuration to your playbook:

[source,yaml]
----
ui:
  bundle:
    url: https://github.com/rhpds/showroom_theme_summit/releases/download/summit-connect-2024/ui-bundle.zip
----

== Showing information on the sidebar

The sidebar will show a simple box with the SSH command and the password for the bastion if specific asciidoc attributes
are set: *page-ssh-command*, *page-ssh-password*

== Add Additional Links

You can add links to external content in the convenient "Links" drop-down on the upper-right of the UI.

../content/antora.yml
[source,yaml]
----
asciidoc:
  attributes:
    page-links:
    - url: https://redhat.com
      text: Red Hat
    - url: https://www.redhat.com/en/summit
      text: Summit
----

== Add a User menu entry

Similar to the external links, you can have a new menu entry with the name of the user

../content/antora.yml
[source,yaml]
----
asciidoc:
  attributes:
    user: 'User X'
----